export const ENV = 'ENV';
export const SWAGGER = 'SWAGGER';

export const CAR_MANAGE_CAR_VIEW = 'CAR_MANAGE_CAR_VIEW';
export const CAR_MANAGE_CAR_ADD = 'CAR_MANAGE_CAR_ADD';
export const CAR_MANAGE_CAR_EDIT = 'CAR_MANAGE_CAR_EDIT';
export const CAR_MANAGE_CAR_DELETE = 'CAR_MANAGE_CAR_DELETE';
export const CAR_MANAGE_CAR_APPROVE_CAR = 'CAR_MANAGE_CAR_APPROVE_CAR';
export const CAR_MANAGE_CAR_APPROVE_CONTAINMENT_ACTION_PLAN =
  'CAR_MANAGE_CAR_APPROVE_CONTAINMENT_ACTION_PLAN';
export const CAR_MANAGE_CAR_APPROVE_RCA_CORRECTIVE_ACTION_PLAN =
  'CAR_MANAGE_CAR_APPROVE_RCA_CORRECTIVE_ACTION_PLAN';
export const CAR_MANAGE_CAR_APPROVE_IMPLEMENTATION_ACTIONS =
  'CAR_MANAGE_CAR_APPROVE_IMPLEMENTATION_ACTIONS';
export const CAR_MANAGE_CAR_APPROVE_IMPLEMENTATION_OF_CORRECTIVE_ACTIONS =
  'CAR_MANAGE_CAR_APPROVE_IMPLEMENTATION_OF_CORRECTIVE_ACTIONS';
export const CAR_MANAGE_CAR_VERIFY_EFFECTIVENESS_OF_CORRECTIVE_ACTIONS =
  'CAR_MANAGE_CAR_VERIFY_EFFECTIVENESS_OF_CORRECTIVE_ACTIONS';
export const CAR_MANAGE_CAR_CLOSE_CAR = 'CAR_MANAGE_CAR_CLOSE_CAR';
export const CAR_MANAGE_CAR_ADMIN_PRIVILEGE_CAR =
  'CAR_MANAGE_CAR_ADMIN_PRIVILEGE_CAR';

export const CAR_TASK_ADD = 'CAR_TASK_ADD';
export const CAR_TASK_EDIT = 'CAR_TASK_EDIT';
export const CAR_TASK_VIEW = 'CAR_TASK_VIEW';
export const CAR_TASK_DELETE = 'CAR_TASK_DELETE';

export const CAR_CUSTOM_ATTRIBUTE_ADD = 'CAR_CUSTOM_ATTRIBUTE_ADD';
export const CAR_CUSTOM_ATTRIBUTE_EDIT = 'CAR_CUSTOM_ATTRIBUTE_EDIT';
export const CAR_CUSTOM_ATTRIBUTE_VIEW = 'CAR_CUSTOM_ATTRIBUTE_VIEW';

export const CAR_SYSTEM_ATTRIBUTE_EDIT = 'CAR_SYSTEM_ATTRIBUTE_EDIT';
export const CAR_SYSTEM_ATTRIBUTE_VIEW = 'CAR_SYSTEM_ATTRIBUTE_VIEW';

export const CAR_SYSTEM_CODES_ADD = 'CAR_SYSTEM_CODES_ADD';
export const CAR_SYSTEM_CODES_EDIT = 'CAR_SYSTEM_CODES_EDIT';
export const CAR_SYSTEM_CODES_VIEW = 'CAR_SYSTEM_CODES_VIEW';

export const CAR_NON_CONFORMANCE_LEVEL_ADD = 'CAR_NON_CONFORMANCE_LEVEL_ADD';
export const CAR_NON_CONFORMANCE_LEVEL_EDIT = 'CAR_NON_CONFORMANCE_LEVEL_EDIT';
export const CAR_NON_CONFORMANCE_LEVEL_VIEW = 'CAR_NON_CONFORMANCE_LEVEL_VIEW';

export const CAR_WORKFLOW_EDIT = 'CAR_WORKFLOW_EDIT';
export const CAR_WORKFLOW_VIEW = 'CAR_WORKFLOW_VIEW';
